### ISSUE TITLE
Change repo's name

### ISSUE THREAD

**Issue by ghpabs** [ghpabs/angular2-seed-project#42]
See https://github.com/mgechev/angular2-seed/issues/298

As to show appreciation to everyone's input in the open-source community, I'm looking for a new name for this repo. 

Please put your suggestions here and the most popular one will be the winner.

**Comment by NathanWalker** [comment]
`angular2-seed-hero-app` or `angular2-hero-app-seed`

:+1: great effort and sorry for any frustrations. I can help with a rename if that's the route you go here.
I like keeping the `angular2-seed` prefix as that could help seed projects stand out amongst samples, etc.

**Comment by ghpabs** [comment]
The project has gone through a couple of updates including the hero app which was removed.

I've changed the repo to [ghpabs/angular2-seed-project](https://github.com/ghpabs/angular2-seed-project/).
