### ISSUE TITLE
Why are your dev scripts explicitly laid out?

### ISSUE THREAD

**Issue by mbalex99** [ghpabs/angular2-seed-project#47]
Why are your dev script include explicitly laid out while your prod scripts are wildcard-referenced?

Great job. I LOVE IT!

```javascript
module.exports = {
	dev: {
		// Files to be included in the `index.html`.
		includes: [
			'build/lib/system.js',
			'build/lib/Rx.js',
			'build/lib/angular2-polyfills.js',
			'build/lib/angular2.dev.js',
			'build/lib/router.dev.js',
			'build/lib/http.dev.js',
            'build/lib/lodash.js',
			'build/css/app.css'
		],

		// Files to be processed by Gulp.
		libs: {
			js: [
				'node_modules/systemjs/dist/system.js',
				'node_modules/rxjs/bundles/Rx.js',
				'node_modules/angular2/bundles/angular2-polyfills.js',
				'node_modules/angular2/bundles/angular2.dev.js',
				'node_modules/angular2/bundles/router.dev.js',
				'node_modules/angular2/bundles/http.dev.js',
                'node_modules/lodash/index.js'
			]
		}
	},

	prod: {
		// Files to be included in the `index.html`.
		includes: [
			'build/lib/*',
			'build/css/*'
		],

		// Files to be processed by Gulp.
		libs: {
			js: [
				'node_modules/systemjs/dist/system.js',
				'node_modules/rxjs/bundles/Rx.min.js',
				'node_modules/angular2/bundles/angular2-polyfills.min.js',
				'node_modules/angular2/bundles/angular2.min.js',
				'node_modules/angular2/bundles/router.min.js',
				'node_modules/angular2/bundles/http.min.js',
                'node_modules/lodash/index.js'
			]
		}
	}
};
```

**Comment by ghpabs** [comment]
Hey @mbalex99 thanks!

Good question, there's no reason in particular for using wildcard in the glob there. We can change it to read as per below.

```
includes: [
    'build/lib/libs.js',
    'build/css/app.css'
],
```

Would you like to create a PR? If not it's okay, I'll change it later :-)

**Comment by mbalex99** [comment]
Ah no I mean... I'm trying to figure out the best practice for adding another library. For example. If I 
did 
```shell
npm install lodash --save
```
and I wanted to add lodash to my Angular2 runtime...

Wouldn't I just reference the `node_modules/lodash/index.js` file in the `libs` array for both dev and prod? 
Do I ever have to modify the `includes` array? 

Whats your take? If you have one, can you mention it in the README.md?

**Comment by ghpabs** [comment]
Right, so after installing the package, you add `'node_modules/lodash/index.js'` to both dev and prod libs array. Then you also need to make it available on the page so you add `'build/lib/index.js'` to dev includes array.

Lodash is an interesting case scenario because its main file is called `index.js` which works but isn't ideal in our flat folder structure - it could cause conflicts with another lib also called `index.js` in the future.

**Comment by mbalex99** [comment]
Okay maybe it's escaping me but why would libs and includes ever be
different?

**Comment by ghpabs** [comment]
It was laid out like this for the case where you want Gulp to copy a file to the build folder but you don't necessarily want to inject it in the page - the file might be loaded later via a module loader like require our SystemJS.

The `include` array also has the CSS files what you be injected in the page.

That said, I'm planning to come up with a better setup for all files and paths used by Gulp.

Feel free to add your suggestions or thoughts.

**Comment by ghpabs** [comment]
Okay, early morning here I think I might have missed the point of your very first question.

We can't use wildcard refs in the dev includes because it needs to follow a loading order - eg router needs to be loaded before angular2 and so on.

**Comment by mbalex99** [comment]
Ahhh perfect I understand now... cool thanks!

I guess the only thing would be the conflict of names... 
I guess you can include a 
```javascript
{
     src: 'node_modules/lodash/index.js'
     rename: 'lodash.js'
}
```
Check... 
What do you think?

**Comment by ghpabs** [comment]
Done in https://github.com/ghpabs/angular2-seed-project/commit/93bf35849904ad7d9aa9c9d26d12f49020065f8c.

Before:
- JS vendor libs had to be written twice under `libs` and `includes`. 
- `build/libs` folder had flat structure.

After:
- JS vendor libs only need to be written once per env - see [`gulpfile.paths.js`](https://github.com/ghpabs/angular2-seed-project/blob/93bf35849904ad7d9aa9c9d26d12f49020065f8c/gulpfile.paths.js).
- `build/libs` will maintain `node_modules` folder structure.
