### ISSUE TITLE
Question: Does gulpfile.path.js really needs dev and prod ?

### ISSUE THREAD

**Issue by maxime1992** [ghpabs/angular2-seed-project#48]
In the `gulpfile.path.js` we can find 2 envs : Dev and prod.

We basically put the same files here but we only change the dev version to the minimified one for prod.

Does it make sense ? I mean, all the assets are compiled (css+js) when building the project right ?

So why do we have to differenciate them ? We should simply use the non minimified version and let gulp build the whole thing minimified, shouldn't we ?

It would avoid this duplication.

**Comment by ghpabs** [comment]
That's a fair point.

I wonder if there will be a case where dev and prod libs are actually different other than just minified versions of the original file.

Maybe a debug lib that would only be used during development?

I'm not sure if it's safe to assume *all* dev and prod libs will *always* be the same.

Thoughts?

**Comment by maxime1992** [comment]
No you're right it make sense.

If i don't use dev libs i'll just do 
```
let libsArray =  [
				'node_modules/systemjs/dist/system.js',
				'node_modules/es6-shim/es6-shim.min.js',
				'node_modules/rxjs/bundles/Rx.min.js',
				'node_modules/angular2/bundles/angular2-polyfills.min.js',
				'node_modules/angular2/bundles/angular2.min.js',
				'node_modules/angular2/bundles/router.min.js',
				'node_modules/angular2/bundles/http.min.js'
			];

module.exports = {
	dev: {
		libs: {
			js: libsArray
		}
	},

	prod: {
		libs: {
			js: libsArray
		}
	}
};
```

**Comment by ghpabs** [comment]
Another option would be the ES6 spread operator.

Example:

```
let baseLibs =  [
    'node_modules/systemjs/dist/system.js',
    'node_modules/es6-shim/es6-shim.min.js',
    'node_modules/rxjs/bundles/Rx.min.js',
    'node_modules/angular2/bundles/angular2-polyfills.min.js',
    'node_modules/angular2/bundles/angular2.min.js',
    'node_modules/angular2/bundles/router.min.js',
    'node_modules/angular2/bundles/http.min.js'
];

module.exports = {
    dev: {
        libs: {
            js: [
                ...baseLibs,
                'node_modules/dev-only-lib/index.js'
            ]
        }
    },

    prod: {
        libs: {
            js: baseLibs
        }
    }
};
```

**Comment by maxime1992** [comment]
Aaaah i like it ! 
I reopen the issue and let you close it with a commit if you want ... :+1: !

**Comment by ghpabs** [comment]
Cool thanks, I'll get it sorted later on today.
