### ISSUE TITLE
Modifying a file causes .js files to populate the src/scripts directory when watching files

### ISSUE THREAD

**Issue by nathasm** [ghpabs/angular2-seed-project#50]
I'm not sure if it is just me, but when I run just `gulp unit` or `gulp build` everything works as expected.

However, when I run `gulp build serve` and then modify a file, the unit tests kick off, but the source tree is then littered with the converted .js files.

Is that by design? I haven't figured out why there is a difference between running `gulp unit` `gulp build` or `gulp serve`

**Comment by ghpabs** [comment]
Interesting! It's def not the design. Let me have a look at it.

**Comment by ghpabs** [comment]
Nope, I can't reproduce it here.

Maybe it is related to your environment - eg. IDE auto transpiling TS files?

**Comment by nathasm** [comment]
*facepalm* Yes! That would explain it! I was able to touch a file and see everything kick off but no .js files. Edit a file and they would show up. I should have realized it was vim leaving stuff behind.

**Comment by ghpabs** [comment]
Haha cool no worries.
