### ISSUE TITLE
Implement a type definition manager for TypeScript

### ISSUE THREAD

**Issue by ghpabs** [ghpabs/angular2-seed-project#51]
[Typings](https://github.com/typings/typings) seems to be a promising alternative.

More info:
- [Typings vs TSD](https://github.com/typings/typings/issues/72)
- [TSD Future](https://github.com/DefinitelyTyped/tsd/issues/150)

**Comment by maxime1992** [comment]
I think it would be cool to make a list (or even an array if supported) of advantages and disadvantages for both. A sort of comparison to understand a little bit more.

**Comment by ghpabs** [comment]
Sure good idea. See 'More info' in the original post.

**Comment by gdi2290** [comment]
:+1: typings

**Comment by ghpabs** [comment]
Done in https://github.com/ghpabs/angular2-seed-project/commit/9214cf77391652c89ae98f39149f5b33ff32fc6b and polished up in https://github.com/ghpabs/angular2-seed-project/commit/7b001b2e75eddb365d0319ccfec9805d3bdca20f.
