### ISSUE TITLE
postinstall script 'typings install' fails.

### ISSUE THREAD

**Issue by pas2al** [ghpabs/angular2-seed-project#54]
After cloning the project, npm install fails:
`sh: typings: command not found
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-seed@1.1.0 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-seed@1.1.0 postinstall script 'typings install'.`

**Comment by ghpabs** [comment]
You'll need to install Typings as global first.

`npm install typings -g`

Sorry about that, it should probably be documented or automatically installed when you first run `npm install`.

Let me know how it goes.

**Comment by pas2al** [comment]
Thanks for the hint, after installing typings, i get another error:
`/angular2-seed-project/gulpfile.js:102
	var result = gulp.src(['typings/main.d.ts', ...filesGlob])
	                                            ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)`

**Comment by ghpabs** [comment]
That's because of ES6 - You'll need NodeJS 5.x for that. Or you can use `.concat()` instead.

**Comment by pas2al** [comment]
Perfect. Thanks! What about the pull request. Should we change something?

**Comment by ghpabs** [comment]
All good mate.

Regards the PR, I'll need to speak to the guys at Typings because ideally the package should be installed globally - so I'm thinking we'll need to set a hook script in the `package.json`.

For example:

```
"scripts": {
  "preinstall": "npm i typings -g"
}
```

**Comment by ghpabs** [comment]
@pas2al Any thoughts? Let me know if you're happy to send a PR with the script above. Cheers.

**Comment by pas2al** [comment]
I am going to test it later and send you a new pr ;-)

**Comment by ghpabs** [comment]
Sounds like a plan - thanks for contributing :-)

**Comment by ghpabs** [comment]
Fixed at #55.

**Comment by keithalewis** [comment]
What if installing typings globally is not an option? There is no file/script/executable called 'typings' in the distribution.

**Comment by ghpabs** [comment]
> What if installing typings globally is not an option?

You don't **have** to install `typings` globally. But that'd be the same as saying you don't want to install `npm` globally.

In theory you could still download or get the definition files `d.ts` from somewhere else - perhaps manually?

**Comment by keithalewis** [comment]
I installed the TypeScript compiler locally  and added the directory to `tsc` to my PATH. Thanks for pointing out I can do things manually. Can you tell me how to run typings when it is not installed globally?

**Comment by ghpabs** [comment]
Typings is a definition manager for TypeScript. If you don't have it installed then you need to get the definition files manually. Imagine for example, if you didn't have npm and you wanted to install a package - let's say jQuery - you'd have to go get it from somewhere else on the internet.

For more info I'd recommend [TypeScript](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) and [Typings](https://www.npmjs.com/package/typings) official documentation.

**Comment by HillTravis** [comment]
I would argue that installing Typings globally is **not** ideal. What if you have multiple projects, and one requires a certain version of Typings, while another project requires a different version?

When you install it locally to the project, it creates a binary in `node_modules/.bin/typings`. Then you can create an NPM script with the same name (i.e. `"scripts": { "typings": "typings" }`) and change your `postinstall` script to `npm run typings install`.

This way, Typings is installed locally instead of globally (reducing the chance of conflicts between projects) and this project is set up correctly with just the `npm install` command.

**Comment by keithalewis** [comment]
+1

**Comment by jimbuck** [comment]
Installing globally is unnecessary, as [any modules that define executable scripts will be added to **path**](https://docs.npmjs.com/misc/scripts#path) for that command. So @HillTravis is correct, but his suggestion can be simplified even more. 

You don't need to create the `"typings":"typings"` script and call `npm run typings install`. All you need is `typings` listed under `devDependencies` and then `"postinstall": "typings install"` under scripts.

**Comment by HillTravis** [comment]
@JimmyBoh Thanks! I didn't realize it was added to the path. However, if I wanted to run `typings install` alone from the command line, would I still need `"typings":"typings"` to avoid having to type `./node_modules/.bin/typings`, or is there some other trickery of which I'm unaware?

**Comment by jimbuck** [comment]
All executable scripts will be added to **path** when used via an `npm` script, but otherwise you must install it globally to use it globally. It's somewhat unfortunate to have to type the path like that, but it's far easier on the contributors who don't need to mess with it at all, and much safer when it comes to breaking version changes (I'm looking at you typings@1.0).
