### ISSUE TITLE
Angular2 breaking when minified - SystemJS

### ISSUE THREAD

**Issue by ghpabs** [ghpabs/angular2-seed-project#56]
Angular 2 beta has reports of being broken after minification.

See: https://github.com/angular/angular/issues/6380.

**Error message:**
```
EXCEPTION: 
libs.js:27 Error: No Directive annotation found on t
    at new t (libs.js:15)
    at e.resolve (libs.js:14)
    at e.getResolvedDirectiveMetadata (libs.js:17)
    at Function.e.create (libs.js:16)
    at eval (viewFactory_t:773)
    at Object.A [as evalExpression] (libs.js:11)
    at e._createViewFactoryRuntime (libs.js:28)
    at libs.js:28
    at n.run (libs.js:10)
    at n.run (libs.js:20)
```

**Workaround:**

Set `uglify.mangle` to `false` for now.

See: https://github.com/ghpabs/angular2-seed-project/commit/e45443c4e9d2069a1e047c9f6df53ee651a16eae#diff-b9e12334e9eafd8341a6107dd98510c9R112.

**Comment by ghpabs** [comment]
Set `uglify.mangle` to `false` for now - workaround.

See: https://github.com/ghpabs/angular2-seed-project/commit/e45443c4e9d2069a1e047c9f6df53ee651a16eae#diff-b9e12334e9eafd8341a6107dd98510c9R112.

**Comment by ghpabs** [comment]
My bad - the issue was not solved by `beta.7`.

**Comment by jeveloper** [comment]
What about Angular 2 beta 9?

**Comment by ghpabs** [comment]
It's still the same in beta 9.

**Comment by unlight** [comment]
Is it angular2 issue?
The problem still happens even using [https://github.com/systemjs/builder](systemjs/builder), is it?

**Comment by kyle-007** [comment]
Yes it is an angular2 issue

**Comment by ghpabs** [comment]
We'll go with setting `mangle` to `false` as advised by Igor Minar [here](https://github.com/angular/angular/issues/6380#issuecomment-203247147).

> to fix Angular applications that use uglify we should either recommend that people turn property renaming (mangling) off, or that they whitelist all directive/component classes.
