### ISSUE TITLE
Split gulpfile.js into partial files

### ISSUE THREAD

**Issue by kevincaradant** [ghpabs/angular2-seed-project#61]
Hi

It may be a good idea to split your gulp file as it is getting bigger and bigger ;)

**Comment by kevincaradant** [comment]
I have no much time to split your gulpfile in the moment :/ . 

So i can just to give you my repository where i split my gulp file. it's not very complicated , just take time ;): https://github.com/kevincaradant/web-template/commit/585cd47728c0a2d64bd321f78b53dc0358073951

**Comment by ghpabs** [comment]
It's all good Kévin. I'm working on it as we speak ;-)

**Comment by kevincaradant** [comment]
With pleasure ;)

**Comment by ghpabs** [comment]
Here's the new branch: https://github.com/ghpabs/angular2-seed-project/tree/feature/gulp-split
