### ISSUE TITLE
Implement Material Design 2

### ISSUE THREAD

**Issue by ghpabs** [ghpabs/angular2-seed-project#62]
Official repo: https://github.com/angular/material2

Documentation is very lacking as of 23/02/2016.

**Comment by pas2al** [comment]
Of course i would like to help ;-)

**Comment by ghpabs** [comment]
Thanks Pascal. Would you like to be added as contributor and work together with @maxime1992 on a feature branch? I can help if you guys need anything.

**Comment by pas2al** [comment]
Sure, sounds great!

**Comment by ghpabs** [comment]
Added you and @maxime1992 as collabs now. :-)

**Comment by maxime1992** [comment]
Good to me ! I love material design but how do we start without any doc ?

**Comment by ghpabs** [comment]
Well, that's a good point. Maybe we need to wait a bit longer before adventuring ourselves into it.

**Comment by pas2al** [comment]
:+1:

**Comment by ghpabs** [comment]
The ngMaterial 2 is in really early stages atm - only 4 components in the master branch and no other branches are visible either. 

I don't know how long it'll take until we can actually do something with it. So I'll close the issue for now - I'm happy to reopen it later on when the project is more mature.

**Comment by maxime1992** [comment]
Hey guys I just found this tweet of @bradlygreen : https://twitter.com/bradlygreen/status/708001797277790208?s=09
:+1
