### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by buehler** [ghpabs/angular2-seed-project#65]
Hey there

I'm using your angular seed to compile an angular2 project for myself. Now, everything works fine, until I wanna use gulp serve. The watcher runs and after the first compilation, the second one crashes with an out of memory exception. I'm searching since 4 hours, but nothing does solve the problem :cry:

Any ideas?

Cheers
Chris

- Node Version: `v5.7.0`
- NPM Version: `3.6.0`
- Gulp CLI version: `0.4.0`
- Gulp Local version: `4.0.0-alpha.2`
- Typings version: `0.6.8`

**Comment by ghpabs** [comment]
No worries - I'll see if I can reproduce it here. 

What's your OS and IDE? Is the watcher triggered more than once when you save a `.ts` file?

**Comment by buehler** [comment]
OSX El Capitan 10.11.3
IDE is IntelliJ

Yea sometimes it is triggered twice. But the OOM error happens anyway :-) Even if the typescript task is called once.

The first time the compiler runs, it takes 17s, which is a long time :sweat_smile: 
After that, the second run crashes with OOM:

```
[15:21:28] Starting 'default'...
[15:21:28] Starting 'develop'...
[15:21:28] Starting 'build'...
[15:21:28] Starting 'clean'...
[15:21:28] Finished 'clean' after 25 ms
[15:21:28] Starting '<parallel>'...
[15:21:28] Starting 'scss'...
[15:21:28] Starting 'typescript'...
[15:21:29] css all files 146.62 kB
[15:21:30] sass all files 4.44 kB
[15:21:31] Finished 'scss' after 2.87 s
src/shared/services/resource.service.ts(65,73): error TS2345: Argument of type '(x: number, ix: number) => R' is not assignable to parameter of type '(x: number, ix: number) => Observable<any>'.
  Type 'R' is not assignable to type 'Observable<any>'.
[15:21:47] TypeScript: 1 semantic error
[15:21:47] TypeScript: emit succeeded (with errors)
[15:21:47] typescript all files 96.43 kB
[15:21:47] Finished 'typescript' after 19 s
[15:21:47] Finished '<parallel>' after 19 s
[15:21:47] Starting 'assets'...
[15:21:47] fonts all files 215.72 kB
[15:21:47] libs all files 2.82 MB
[15:21:47] Finished 'assets' after 164 ms
[15:21:47] Starting 'index'...
[15:21:48] gulp-inject 22 files into index.html.
[15:21:48] Finished 'index' after 131 ms
[15:21:48] Starting 'typedoc'...
Rendering [========================================] 100%
[15:21:52] Finished 'typedoc' after 4.42 s
[15:21:52] Finished 'build' after 24 s
[15:21:52] Starting 'serve'...
[15:21:52] Starting 'watch'...
```

second run:

```
[15:23:31] Starting 'typescript'...

<--- Last few GCs --->

  244379 ms: Mark-sweep 1375.2 (1455.7) -> 1379.5 (1455.7) MB, 1249.9 / 0 ms [allocation failure] [GC in old space requested].
  245609 ms: Mark-sweep 1379.5 (1455.7) -> 1379.5 (1455.7) MB, 1230.6 / 0 ms [allocation failure] [GC in old space requested].
  246852 ms: Mark-sweep 1379.5 (1455.7) -> 1372.3 (1455.7) MB, 1242.6 / 0 ms [last resort gc].
  248122 ms: Mark-sweep 1372.3 (1455.7) -> 1374.7 (1455.7) MB, 1270.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1053d39e3ac1 <JS Object>
    2: objectTypeRelatedTo(aka objectTypeRelatedTo) [/Users/christoph/Documents/Development/hive-cms/frontend/node_modules/typescript/lib/typescript.js:19809] [pc=0x27aca5717e16] (this=0x1053d3904189 <undefined>,source=0x212f508eab9 <a TypeObject with map 0x109fbe2d7781>,originalSource=0x212f508eab9 <a TypeObject with map 0x109fbe2d7781>,target=0x5a42f067081 <a TypeObject with map 0x32d50bf2680...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    47511 abort      gulp
```

Stuff I did: 
- trying to add gulp-cached to reduce compilation time
- Changed the output directory from `build/` to `../backend/client`

The rest is pretty much the seed with my code in it.

Cheers

**Comment by ghpabs** [comment]
Okay thanks - I'll have a look at it now.

Did the problem start after you implemented `gulp-cached`?

**Comment by buehler** [comment]
Thank you!
No the problem was even before

**Comment by buehler** [comment]
As a hint, I experienced a similar problem with webpack. The typescript compiler ran into an OOM aswell. Could that be a problem with the glob or so?

**Comment by ghpabs** [comment]
Can you confirm when you cloned the seed project? I couple of changes were made in the last few days - including changes to the watcher glob.

**Comment by buehler** [comment]
I cloned it today :-/

It seems, the problem only happens, when I use the watcher

**Comment by ghpabs** [comment]
I'm on OSX El Capitan 10.11.3 and my IDE is Atom - I don't think the IDE really matters in this case but the watcher here is always only triggered once.

Maybe it's something to do with Node? Perhaps try uninstalling Node and npm and installing it again.

**Comment by ghpabs** [comment]
BWT - I haven't been able to reproduce the issue here. 

![image](https://cloud.githubusercontent.com/assets/3250667/13530806/2190e858-e21b-11e5-912d-88fd57ad6d42.png)

**Comment by buehler** [comment]
F*ck. 

well.. I'll just try to use IntelliJ for compiling then. I don't find any solution :)

Thank you very much for investigating!

**Comment by ghpabs** [comment]
Did you find a solution though?

**Comment by buehler** [comment]
Yeah more or less, I compile the typescript stuff through IntelliJ now (for the dev-env). Let's see how this works :)

**Comment by ghpabs** [comment]
Hmmm okay - Gulp does more than just transpiling TS to JS. See `gulp-typescript` for more info: https://github.com/ghpabs/angular2-seed-project/blob/master/tasks/gulp-typescript.js

**Comment by buehler** [comment]
Yea, the sourcemaps can be generated by TSC and the inline ngtemplates are deactivated. But well, at least I can work

**Comment by ghpabs** [comment]
Cool!
