### ISSUE TITLE
fix: Some files have bad carriage return

### ISSUE THREAD

**Issue by maxime1992** [ghpabs/angular2-seed-project#68]
Those 4 files : 
src/fonts/Roboto-Bold.ttf
src/fonts/Roboto-Light.ttf
src/fonts/Roboto-Thin.ttf
src/images/angular2-seed-logo.png

have carriage return defined for windows and git wants to convert them.
It is also a problem with rebase (blocked).
`git reset --hard HEAD` doesn't do anything (???)

**Comment by ghpabs** [comment]
Fixed by https://github.com/ghpabs/angular2-seed-project/commit/1c08a1499248535efa2dd4f83b72a76e1815a29a
