### ISSUE TITLE
Implement incremental builds

### ISSUE THREAD

**Issue by unlight** [ghpabs/angular2-seed-project#71]
You are using Gulp 4 which is good. But what about it's new API `since` and `lastRun`.
Related articles:
http://blog.reactandbethankful.com/posts/2015/05/01/building-with-gulp-4-part-4-incremental-builds/
http://fettblog.eu/gulp-4-incremental-builds/

**Comment by ghpabs** [comment]
Thanks for bringing it up. I'll have a look at it in the next couple of days.

**Comment by ghpabs** [comment]
FYI - The Gulp task for TypeScript is already using incremental compilation.

See documentation here: https://www.npmjs.com/package/gulp-typescript#incremental-compilation
See implementation here: https://github.com/ghpabs/angular2-seed-project/blob/master/tasks/gulp-typescript.js#L7

I'm still looking at improving the performance for other tasks.

**Comment by unlight** [comment]
Yeah, I red this. I though why compilation is so slow.
I've just checked `gulp-typescript` and raised an issue https://github.com/ivogabe/gulp-typescript/issues/316
I think, this is reason of slowness.

**Comment by unlight** [comment]
Consider to add option `noExternalResolve: true`.
Now it compiles much faster, but I get multiple errros like
```
error TS2304: Cannot find name 'module'
```
I'll continue to dig deeper...

**Comment by ghpabs** [comment]
I've implemented incremental build for images and fonts. See https://github.com/ghpabs/angular2-seed-project/commit/ed2e9f0f9b7b26d3563345228646190639203353.

The only one remaining is Sass - I [asked the `gulp-sass`](https://github.com/dlmanning/gulp-sass/issues/461) team if it's already done by default but I don't think it is. I tried using `gulp-memory-cache` but then I came across [this issue](https://github.com/troch/gulp-memory-cache/issues/2).

**Comment by ghpabs** [comment]
@unlight @iamthes I saw you guys did some work on your fork `angular2-blank-project`. Did you solve the incremental compilation issues?

**Comment by unlight** [comment]
Hi. What kind of issues? 
[Definition files is not cached by gulp-typescript](https://github.com/ivogabe/gulp-typescript/issues/316) is still issue for me.
But I did not encounter any other compilation issues:
https://github.com/troch/gulp-memory-cache/issues/2 - no such error for me

**Comment by ghpabs** [comment]
Cool - I see you optimised the build process quite a lot. I'll try to copy back some of it to this project.
