### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by sumpton** [ghpabs/angular2-seed-project#74]
Hi, and thank you for your work on this project.

It appears to me that there is a tiny typo in the README. The first version number looks transposed.

| Gulp CLI   | 0.4.x   | `npm install gulpjs/gulp-cli#4.0 -g`  |

**Comment by ghpabs** [comment]
Dupe https://github.com/ghpabs/angular2-seed-project/pull/73.

> Let me know what you think - happy to reopen if I got it wrong.
