### ISSUE TITLE
ng2-bootstrap not loading properly

### ISSUE THREAD

**Issue by minchomilev** [ghpabs/angular2-seed-project#75]
What should I do, to import ng2-bootstrap and moment  properly into the template.
If I put 'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js' into gulpfile.env.js
I am getting this errros:

SyntaxError: expected expression, got '<'
<!DOCTYPE html>
localhost:8080                                     (line 1)
SyntaxError: expected expression, got '<'
	Evaluating http://localhost:8080/moment
	Error loading http://localhost:8080/js/bootstrap.js
	: callback.apply(applyThis, applyArgs);

And the files moment.js and ng2-bootstrap are not loaded.

**Comment by ghpabs** [comment]
Not sure what it can be. Would you like to fork the project and push your changes so I can see the code?

**Comment by minchomilev** [comment]
Hi,
this is my forked repo:

https://github.com/minchomilev/angular2-seed-project

Thanks
Mincho

**Comment by ghpabs** [comment]
Okay, so the issue isn't really related to this seed project. 

Anyway, here it goes...

1. Here we can see other people have come across the same problem: https://github.com/valor-software/ng2-bootstrap/issues/156.
2. Which leads us to this: https://github.com/valor-software/ng2-bootstrap#quick-start.
3. We can then see that we're missing the SystemJS mapping:
```js
map: {
  moment: 'libs/node_modules/moment/moment.js'
}
```
4. Lastly, make sure you also add `moment` to `baseLibs`.
```js
let baseLibs = [
  ...
  'node_modules/moment/moment.js',
  'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.js'
];
```
