### ISSUE TITLE
Three dot notation in gulpfile.env.js

### ISSUE THREAD

**Issue by pas2al** [ghpabs/angular2-seed-project#78]
What is this three dot notation in gulpfile.env.js:27 and gulp-index.js:15? Because i am not able the boot the project with this "syntax errors".

Regarding our README, it should be possible the easily start the project, what isn't the case atm.
$ git clone https://github.com/ghpabs/angular2-seed-project.git && cd angular2-seed-project
$ npm install
$ typings install
$ gulp build serve

**Comment by Wobbly-Wibbly** [comment]
It's spread operator. Update your node version.

**Comment by ghpabs** [comment]
That's right, thanks @Wobbly-Wibbly.

Dupe: https://github.com/ghpabs/angular2-seed-project/issues/53.
